<?php

namespace DeskHQ\LaravelWorktree\Config;

use DeskHQ\LaravelWorktree\Exceptions\WorktreeException;

/**
 * The published `config/worktree.php`, with a repository's own values written
 * into it (#58).
 *
 * The generated file is the package's own config file — the same comment blocks,
 * in the same order, saying the same things — with four values replaced. That is
 * the point rather than an implementation detail: what makes this file
 * maintainable afterwards is not the values, which anyone can re-derive, but the
 * paragraphs explaining why `REVERB_PORT` is pinned and what `keep_services`
 * does to a `depends_on`. A generator that emitted a bare array would hand
 * somebody a file they could not edit without going back to the README.
 *
 * So the shipped file is the template, read at run time rather than duplicated
 * here. A comment added to it next month is in the next generated file with
 * nothing to remember, and there is no second copy of it to drift.
 *
 * ## Replacing a value rather than rendering a file
 *
 * Each key is found where it sits and its value replaced up to the comma that
 * ends it, counting brackets and skipping string literals — because the template
 * is PHP, and the thing after `'compose' => ` is four lines long. A key that has
 * gone missing is an error rather than a silently ungenerated value: this file
 * and that one ship together, and them disagreeing is a bug in the package, not
 * in anybody's repository.
 */
final readonly class Stencil
{
    /**
     * The keys generated from `compose.yaml`. Everything else in the file — the
     * slots, the timeouts, the recipe — is the published default, because
     * nothing about a Compose file has an opinion on it.
     *
     * @var list<string>
     */
    public const array Generated = ['port_stride', 'ports', 'env', 'compose'];

    private function __construct() {}

    /**
     * The whole file, ready to be written or printed.
     *
     * @throws WorktreeException when the package's own config file cannot be read or no longer carries a generated key.
     */
    public static function render(Derivation $derivation): string
    {
        $template = self::template();

        $values = [
            'port_stride' => (string) $derivation->portStride,
            'ports' => self::list($derivation->ports, 4),
            'env' => self::environment($derivation),
            'compose' => self::compose($derivation),
        ];

        foreach (self::Generated as $key) {
            $template = self::replace($template, $key, $values[$key]);
        }

        return self::annotate($template, $derivation);
    }

    /**
     * The package's own copy of the file, which is the one `vendor:publish`
     * would have copied — not whatever the repository already has, which is the
     * file being replaced.
     */
    private static function template(): string
    {
        $path = dirname(__DIR__, 2).'/'.Schema::File;
        $template = @file_get_contents($path);

        if ($template === false) {
            throw new WorktreeException("could not read this package's own $path to generate from");
        }

        return $template;
    }

    /**
     * The note that says where the values came from, and — as plainly as the
     * file says everything else — the three things they cannot be.
     */
    private static function annotate(string $file, Derivation $derivation): string
    {
        // Wrapped here rather than left to run off the side: this list is as
        // long as the repository is, and it is the one line of the note somebody
        // reads twice.
        $services = implode("\n", array_map(
            fn (string $line): string => ' *     '.$line,
            explode("\n", wordwrap(implode(', ', array_keys($derivation->started)), 66)),
        ));

        $note = <<<PHP

            /**
             * Generated by `worktree init` from $derivation->composeFile.
             *
             * The values below are this repository's; every comment around them is the
             * package's, unchanged. What was read: the host port every service
             * publishes, and the services a worktree of this repository starts:
             *
            $services
             *
             * Three things `worktree init` could not know, and did not guess.
             *
             * The bootstrap recipe. `steps` is empty, with the examples still commented
             * out below: nothing about a Compose file says how this application installs
             * itself.
             *
             * Which services a worktree should do without. `MAIL_MAILER=log` and
             * `SCOUT_DRIVER=collection` point a worktree away from services it does not
             * need, and that is a decision about this application rather than a fact
             * about $derivation->composeFile — so `compose.keep_services` below is seeded from
             * what the app service depends on, and nothing is pointed anywhere.
             *
             * What the recipe will start. A service brought up by a bootstrap step —
             * `sail up -d reverb`, and the redis reverb pulls in behind it — is invisible
             * until that step exists, so this first pass saw a smaller set of services
             * than the eventual truth. Re-running `worktree init` once `steps` is written
             * sees the rest, and `worktree doctor` says whether the difference matters.
             * Both are the workflow; neither is a surprise.
             */

            PHP;

        $marker = "\nreturn [";
        $at = strpos($file, $marker);

        if ($at === false) {
            throw new WorktreeException("could not read this package's own ".Schema::File.' to generate from');
        }

        return substr($file, 0, $at + 1).$note.substr($file, $at + 1);
    }

    /**
     * @param  string  $value  The rendered value, without its trailing comma.
     */
    private static function replace(string $file, string $key, string $value): string
    {
        $needle = "\n    '$key' => ";
        $at = strpos($file, $needle);

        if ($at === false) {
            throw new WorktreeException(
                "this package's own ".Schema::File." no longer assigns '$key', so it cannot be generated from"
            );
        }

        $from = $at + strlen($needle);

        return substr($file, 0, $from).$value.substr($file, self::end($file, $from, $key));
    }

    /**
     * Where the value starting at $from ends: the comma that closes it, with
     * every bracket balanced and every quoted string stepped over.
     */
    private static function end(string $file, int $from, string $key): int
    {
        $depth = 0;
        $quote = null;
        $length = strlen($file);

        for ($index = $from; $index < $length; $index++) {
            $character = $file[$index];

            if ($quote !== null) {
                $index += $character === '\\' ? 1 : 0;
                $quote = $character === $quote ? null : $quote;

                continue;
            }

            match (true) {
                $character === "'" || $character === '"' => $quote = $character,
                $character === '[' || $character === '(' => $depth++,
                $character === ']' || $character === ')' => $depth--,
                default => null,
            };

            if ($character === ',' && $depth === 0) {
                return $index;
            }
        }

        throw new WorktreeException(
            "this package's own ".Schema::File." assigns '$key' something this cannot read to the end of"
        );
    }

    /**
     * `env`, with the pinned variables under the one comment that explains why
     * they are not offset like everything above them.
     */
    private static function environment(Derivation $derivation): string
    {
        $lines = [];

        foreach ($derivation->env as $variable => $value) {
            if ($lines !== [] && $variable === array_key_first($derivation->pinned)) {
                $lines[] = '';
                $lines[] = '// dialled inside the container as well as published from it, so pinned';
                $lines[] = "// here and remapped in 'compose.port_overrides' below — trap 1 above";
            }

            $lines[] = "'$variable' => ".self::scalar($value).',';
        }

        return self::block($lines, 4);
    }

    private static function compose(Derivation $derivation): string
    {
        $overrides = [];

        foreach ($derivation->portOverrides as $service => $mappings) {
            $overrides[] = self::scalar($service).' => '.self::list($mappings, 12).',';
        }

        return self::block([
            "'keep_services' => ".self::list($derivation->keepServices, 8).',',
            "'port_overrides' => ".($overrides === [] ? '[]' : self::block($overrides, 8)).',',
        ], 4);
    }

    /**
     * A list on one line, or one entry per line when that line would be long
     * enough to stop being read.
     *
     * @param  list<string>  $values
     * @param  int  $indent  The indentation of the line this value is opened on.
     */
    private static function list(array $values, int $indent): string
    {
        $rendered = array_map(self::scalar(...), $values);
        $inline = '['.implode(', ', $rendered).']';

        if ($values === [] || $indent + strlen($inline) <= 96) {
            return $inline;
        }

        return self::block(array_map(fn (string $value): string => $value.',', $rendered), $indent);
    }

    /**
     * @param  list<string>  $lines
     * @param  int  $indent  The indentation of the line this block is opened on; its contents sit one level in.
     */
    private static function block(array $lines, int $indent): string
    {
        $inside = str_repeat(' ', $indent + 4);

        $body = implode("\n", array_map(
            fn (string $line): string => $line === '' ? '' : $inside.$line,
            $lines,
        ));

        return "[\n".$body."\n".str_repeat(' ', $indent).']';
    }

    private static function scalar(string|int|float|bool|null $value): string
    {
        return match (true) {
            is_string($value) => "'".addcslashes($value, "\\'")."'",
            is_bool($value) => $value ? 'true' : 'false',
            $value === null => 'null',
            default => (string) $value,
        };
    }
}
