<?php

namespace DeskHQ\LaravelWorktree\Shell;

use DeskHQ\LaravelWorktree\Console\PathCommand;
use DeskHQ\LaravelWorktree\Registry\Registry;

/**
 * The script `worktree shell-init` prints: a `wt` function, and completion.
 *
 * Two things, and deliberately only two. `wt` is `cd` around {@see PathCommand},
 * which is what makes that command's bare path on stdout pay off for a person
 * rather than only for a script; the completion is the reason the whole feature
 * is worth having, since the names this package generates are long, come from
 * issue titles, and are exactly the thing nobody holds in their head.
 *
 * Anything with a decision in it belongs in the binary, where it is tested and
 * where a `--json` caller gets the same answer. So the function looks nothing up
 * — it asks `path`, and it asks `create` only when told to — and this file's job
 * is to be a faithful, boring shim around both.
 *
 * ## Generated rather than shipped
 *
 * There is no completion file to install, and no second step after
 * `composer require`. The script names the commands, the flags and the slug
 * arguments that *this* binary has ({@see Vocabulary}), so upgrading the package
 * and re-running the `eval` is the whole of keeping it current — where a copied
 * file would quietly complete the flags of whatever version wrote it.
 *
 * ## Where completion gets its slugs
 *
 * From `~/.laravel-worktree/registry.json`, read with `awk`, and this is the one
 * design decision in here worth defending. The alternative is asking the binary,
 * which costs a PHP start, an anchor, a config read and — once `list` carries a
 * status column — a daemon query, on every press of the Tab key. A completion
 * that takes 300ms is a completion people turn off, and the file is written
 * atomically by one class ({@see Registry}), so a reader sees the whole of one
 * registry or the whole of the other.
 */
final readonly class Script
{
    /**
     * Where the binary is written into the emitted text.
     */
    private const string Binary = '__BINARY__';

    private function __construct(
        private Dialect $dialect,
        private Vocabulary $vocabulary,
        /** The binary this was generated by, absolute. */
        private string $binary,
    ) {}

    public static function for(Dialect $dialect, Vocabulary $vocabulary, string $binary): self
    {
        return new self($dialect, $vocabulary, $binary);
    }

    /**
     * The whole script, ready to be `eval`d.
     */
    public function render(): string
    {
        return str_replace(self::Binary, self::quote($this->binary), implode("\n", [
            $this->preamble(),
            $this->shim(),
            $this->slugs(),
            $this->catalogue(),
            match ($this->dialect) {
                Dialect::Bash => $this->bash(),
                Dialect::Zsh => $this->zsh(),
            },
        ]));
    }

    private function preamble(): string
    {
        return <<<SH
            # laravel-worktree — the 'wt' function, and completion for both names.
            #
            #     eval "\$(__BINARY__ shell-init {$this->dialect->value})"
            #
            # Generated, not installed: this text knows the commands and flags the
            # binary that emitted it has, so re-run the line above after upgrading the
            # package rather than editing anything here.

            SH;
    }

    /**
     * Resolving the binary, and the `wt` function itself.
     */
    private function shim(): string
    {
        return <<<'SH'
            # The binary that generated this, named absolutely, because the whole point
            # is that 'wt' works from wherever the cursor is — including from ~, which
            # is in no repository at all. The failure there is then this package's own
            # message rather than 'command not found'. WORKTREE_BIN overrides it, for a
            # checkout that has since moved.
            __worktree_binary() {
                local binary=${WORKTREE_BIN:-__BINARY__}

                if [ -x "$binary" ]; then
                    printf '%s\n' "$binary"

                    return 0
                fi

                printf 'error: no worktree binary at %s; re-run its shell-init, or set WORKTREE_BIN\n' "$binary" >&2

                return 1
            }

            # wt                             what this repository is holding
            # wt <slug>                      cd into that worktree
            # wt -c|--create <slug> [base]   make it if it is not there, then cd into it
            #
            # The lookup is 'worktree path' and never 'worktree create': a cd that can
            # start a five-minute bootstrap on a typo is a trap, so creating is
            # something you ask for. Everything else is the binary itself — this is a
            # cd, not a second command line.
            wt() {
                # Not 'status': zsh keeps that one for itself, read-only, and a
                # function that assigns to it dies on the spot.
                local binary target code

                binary=$(__worktree_binary) || return 1

                case ${1-} in
                    '')
                        "$binary" list

                        return
                        ;;
                    -c|--create)
                        shift

                        if [ "$#" -eq 0 ]; then
                            printf 'usage: wt --create <slug> [base]\n' >&2

                            return 64
                        fi

                        target=$("$binary" create "$@") || return
                        ;;
                    -h|--help)
                        printf '%s\n' \
                            'wt                             what this repository is holding' \
                            'wt <slug>                      cd into that worktree' \
                            'wt -c|--create <slug> [base]   make it if it is not there, then cd into it' \
                            "anything else is '$binary <command>'" >&2

                        return 0
                        ;;
                    -*)
                        printf "wt takes a worktree, not options; run 'worktree' itself for %s\n" "$1" >&2

                        return 64
                        ;;
                    *)
                        if [ "$#" -gt 1 ]; then
                            printf "wt takes one worktree; run 'worktree' itself for anything else\n" >&2

                            return 64
                        fi

                        # The list, when the slug resolved to nothing — quietly, because
                        # the lookup has already said what went wrong, and a run from
                        # outside a repository would otherwise say the same thing twice.
                        target=$("$binary" path "$1") || {
                            code=$?

                            "$binary" list 2>/dev/null

                            return $code
                        }
                        ;;
                esac

                [ -n "$target" ] || return 1

                cd -- "$target"
            }

            SH;
    }

    /**
     * The slug source, which is the registry file and not the binary.
     */
    private function slugs(): string
    {
        return <<<'SH'
            # Every slug this machine holds, out of the registry the binary writes:
            #
            #     ${WORKTREE_HOME:-$HOME/.laravel-worktree}/registry.json
            #
            # Read rather than asked for. This runs on every press of the Tab key, and a
            # round trip through PHP, git and a config file is the difference between
            # instant and a completion people turn off.
            #
            # Scoped to the repository the cursor is in whenever git can say which one
            # that is, because the registry is machine-global and 'worktree path'
            # refuses an entry belonging to another checkout — offering those would be
            # offering completions that cannot work. When git cannot answer, every slug
            # is offered rather than none.
            __worktree_slugs() {
                local registry=${WORKTREE_HOME:-$HOME/.laravel-worktree}/registry.json
                local repo

                [ -r "$registry" ] || return 0

                # --git-common-dir points at the main checkout's .git from inside a
                # worktree as well as from the checkout, which is the same anchor the
                # binary takes and therefore the same 'repo' every entry records.
                repo=$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null) || repo=
                [ -z "$repo" ] || repo=${repo%/.git}

                awk -v repo="$repo" '
                    {
                        line = $0

                        while (match(line, /"(repo|slug)"[ \t]*:[ \t]*"[^"]*"/)) {
                            field = substr(line, RSTART, RLENGTH)
                            line = substr(line, RSTART + RLENGTH)

                            value = field
                            sub(/^"[a-z]+"[ \t]*:[ \t]*"/, "", value)
                            sub(/"$/, "", value)

                            # An entry records its checkout before it records its slug,
                            # so the repo in hand is always the one this slug is under.
                            if (field ~ /^"repo"/)
                                held = value
                            else if (repo == "" || held == repo)
                                print value
                        }
                    }
                ' "$registry"
            }

            SH;
    }

    /**
     * What completes what, written out of the commands the binary dispatches.
     */
    private function catalogue(): string
    {
        return implode("\n", [
            "__worktree_commands() {\n    printf '%s\\n' ".implode(' ', $this->vocabulary->commands())."\n}\n",
            "__worktree_flags() {\n    case \${1-} in\n".$this->flagCases()."    esac\n}\n",
            "__worktree_arguments() {\n    case \${1-} in\n".$this->argumentCases()."    esac\n}\n",
        ]);
    }

    private function flagCases(): string
    {
        $cases = '';

        foreach ($this->vocabulary->commands() as $command) {
            $flags = $this->vocabulary->flags($command);

            if ($flags !== []) {
                $cases .= "        $command) printf '%s\\n' ".implode(' ', $flags)." ;;\n";
            }
        }

        return $cases;
    }

    private function argumentCases(): string
    {
        $cases = '';
        $slugs = $this->vocabulary->takingSlugs();

        if ($slugs !== []) {
            $cases .= '        '.implode('|', $slugs).") __worktree_slugs ;;\n";
        }

        foreach ($this->vocabulary->commands() as $command) {
            $values = $this->vocabulary->values($command);

            if ($values !== []) {
                $cases .= "        $command) printf '%s\\n' ".implode(' ', $values)." ;;\n";
            }
        }

        return $cases;
    }

    private function bash(): string
    {
        return <<<'SH'
            # A command name, then that command's flags and arguments. The argument is
            # offered only where one goes — after the command itself, or after a flag
            # that takes one — because 'create 441 <TAB>' is a git ref, and completing
            # worktrees into it would be a wrong answer rather than no answer.
            __worktree_complete() {
                local cursor=${COMP_WORDS[COMP_CWORD]}
                local previous=${COMP_WORDS[COMP_CWORD-1]}
                local command='' word index=1

                while [ "$index" -lt "$COMP_CWORD" ]; do
                    word=${COMP_WORDS[index]}

                    case $word in
                        -*) ;;
                        *) command=$word; break ;;
                    esac

                    index=$((index + 1))
                done

                if [ -z "$command" ]; then
                    COMPREPLY=($(compgen -W "$(__worktree_commands)" -- "$cursor"))

                    return
                fi

                case $cursor in
                    -*)
                        COMPREPLY=($(compgen -W "$(__worktree_flags "$command")" -- "$cursor"))

                        return
                        ;;
                esac

                case $previous in
                    "$command"|-*)
                        COMPREPLY=($(compgen -W "$(__worktree_arguments "$command")" -- "$cursor"))
                        ;;
                    *)
                        COMPREPLY=()
                        ;;
                esac
            }

            # 'wt' takes a worktree where the binary takes a command, so it completes
            # the one thing it accepts, plus the flag that creates.
            __worktree_complete_wt() {
                local cursor=${COMP_WORDS[COMP_CWORD]}

                COMPREPLY=($(compgen -W "$(__worktree_slugs) --create" -- "$cursor"))
            }

            complete -F __worktree_complete worktree
            complete -F __worktree_complete_wt wt
            SH;
    }

    private function zsh(): string
    {
        return <<<'SH'
            # A command name, then that command's flags and arguments. The argument is
            # offered only where one goes — after the command itself, or after a flag
            # that takes one — because 'create 441 <TAB>' is a git ref, and completing
            # worktrees into it would be a wrong answer rather than no answer.
            __worktree_complete() {
                local command='' word
                local -a candidates

                for word in ${words[2,CURRENT-1]}; do
                    case $word in
                        -*) ;;
                        *) command=$word; break ;;
                    esac
                done

                if [[ -z $command ]]; then
                    candidates=(${(f)"$(__worktree_commands)"})
                elif [[ ${words[CURRENT]} == -* ]]; then
                    candidates=(${(f)"$(__worktree_flags $command)"})
                elif [[ ${words[CURRENT-1]} == "$command" || ${words[CURRENT-1]} == -* ]]; then
                    candidates=(${(f)"$(__worktree_arguments $command)"})
                fi

                compadd -- ${candidates:#}
            }

            # 'wt' takes a worktree where the binary takes a command, so it completes
            # the one thing it accepts, plus the flag that creates.
            __worktree_complete_wt() {
                local -a candidates

                candidates=(--create ${(f)"$(__worktree_slugs)"})

                compadd -- ${candidates:#}
            }

            # Skipped rather than failed when the completion system has not been
            # started: an rc file that evals this above its 'compinit' should get a
            # working 'wt' and no completion, not an error on every new shell.
            if whence compdef > /dev/null 2>&1; then
                compdef __worktree_complete worktree
                compdef __worktree_complete_wt wt
            fi
            SH;
    }

    /**
     * $path as one shell word, whatever is in it.
     */
    private static function quote(string $path): string
    {
        return "'".str_replace("'", "'\\''", $path)."'";
    }
}
